# Generated by Django 2.1.7 on 2019-02-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190225_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
