# Generated by Django 2.1.7 on 2019-02-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190223_1755'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealtorModel',
            new_name='Realtor',
        ),
    ]
